permalink: pretty
paginate: 5
version: 1.0.1

title: Jordy Aaldering
tagline: My personal website
description: A website I created for the Big Data course.
url: https://jordyaaldering.github.io/
baseurl: ''

author:
  name: Jordy Aaldering
  email: aalderingjordy@gmail.com
  url: https://jordyaaldering.github.io/

github:
  url: https://github.com/JordyAaldering/JordyAaldering.github.io
  issues: https://github.com/JordyAaldering/JordyAaldering.github.io/issues